const CountDetailActionTypes = {
    REQUEST_DAILY_COUNT_DATA : "REQUEST_DAILY_COUNT_DATA",
    RECEIVE_DAILY_COUNT_DATA : "RECEIVE_DAILY_COUNT_DATA",
    DAILY_COUNT_DATA_FAILURE : "DAILY_COUNT_DATA_FAILURE",
    REQUEST_USER_COUNT_DATA : "REQUEST_USER_COUNT_DATA",
    RECEIVE_USER_COUNT_DATA : "RECEIVE_USER_COUNT_DATA",
    REQUEST_USER_COUNT_BY_DAY_DATA : "REQUEST_USER_COUNT_BY_DAY_DATA",
    RECEIVE_USER_COUNT_BY_DAY_DATA : "RECEIVE_USER_COUNT_BY_DAY_DATA",

    FSC_REQUEST_DAILY_COUNT_DATA : "FSC_REQUEST_DAILY_COUNT_DATA",
    FSC_RECEIVE_DAILY_COUNT_DATA : "FSC_RECEIVE_DAILY_COUNT_DATA",
    FSC_REQUEST_USER_COUNT_DATA : "FSC_REQUEST_USER_COUNT_DATA",
    FSC_RECEIVE_USER_COUNT_DATA : "FSC_RECEIVE_USER_COUNT_DATA",
    FSC_REQUEST_USER_COUNT_BY_DAY_DATA : "FSC_REQUEST_USER_COUNT_BY_DAY_DATA",
    FSC_RECEIVE_USER_COUNT_BY_DAY_DATA : "FSC_RECEIVE_USER_COUNT_BY_DAY_DATA",
}

export default CountDetailActionTypes;