const CountDetailActionTypes = {
    CHG_REQUEST_DAILY_COUNT_DATA : "CHG_REQUEST_DAILY_COUNT_DATA",
    CHG_RECEIVE_DAILY_COUNT_DATA : "CHG_RECEIVE_DAILY_COUNT_DATA",
    CHG_DAILY_COUNT_DATA_FAILURE : "CHG_DAILY_COUNT_DATA_FAILURE",
    CHG_REQUEST_USER_COUNT_DATA : "CHG_REQUEST_USER_COUNT_DATA",
    CHG_RECEIVE_USER_COUNT_DATA : "CHG_RECEIVE_USER_COUNT_DATA",
    CHG_USER_COUNT_DATA_FAILURE : "CHG_USER_COUNT_DATA_FAILURE",
    CHG_REQUEST_USER_COUNT_BY_DAY_DATA : "CHG_REQUEST_USER_COUNT_BY_DAY_DATA",
    CHG_RECEIVE_USER_COUNT_BY_DAY_DATA : "CHG_RECEIVE_USER_COUNT_BY_DAY_DATA",
    CHG_USER_COUNT_BY_DAY_DATA_FAILURE : "CHG_USER_COUNT_BY_DAY_DATA_FAILURE",

    FSC_REQUEST_DAILY_COUNT_DATA : "FSC_REQUEST_DAILY_COUNT_DATA",
    FSC_RECEIVE_DAILY_COUNT_DATA : "FSC_RECEIVE_DAILY_COUNT_DATA",
    FSC_DAILY_COUNT_DATA_FAILURE: "FSC_DAILY_COUNT_DATA_FAILURE",
    FSC_REQUEST_USER_COUNT_DATA : "FSC_REQUEST_USER_COUNT_DATA",
    FSC_RECEIVE_USER_COUNT_DATA : "FSC_RECEIVE_USER_COUNT_DATA",
    FSC_USER_COUNT_DATA_FAILURE : "FSC_USER_COUNT_DATA_FAILURE",
    FSC_REQUEST_USER_COUNT_BY_DAY_DATA : "FSC_REQUEST_USER_COUNT_BY_DAY_DATA",
    FSC_RECEIVE_USER_COUNT_BY_DAY_DATA : "FSC_RECEIVE_USER_COUNT_BY_DAY_DATA",
    FSC_USER_COUNT_BY_DAY_DATA_FAILURE : "FSC_USER_COUNT_BY_DAY_DATA_FAILURE",
}

export default CountDetailActionTypes;