const ProgressPageActionTypes = {
    // Active Locations Breakdown action types
    CHG_OCCUPIED_LOCS_COUNTED_START : 'CHG_OCCUPIED_LOCS_COUNTED_START',
    CHG_OCCUPIED_LOCS_COUNTED_SUCCESS : 'CHG_OCCUPIED_LOCS_COUNTED_SUCCESS',
    CHG_OCCUPIED_LOCS_COUNTED_FAILURE : 'CHG_OCCUPIED_LOCS_COUNTED_FAILURE',
    CHG_OCCUPIED_LOCS_UNCOUNTED_START : 'CHG_OCCUPIED_LOCS_UNCOUNTED_START',
    CHG_OCCUPIED_LOCS_UNCOUNTED_SUCCESS : 'CHG_OCCUPIED_LOCS_UNCOUNTED_SUCCESS',
    CHG_OCCUPIED_LOCS_UNCOUNTED_FAILURE : 'CHG_OCCUPIED_LOCS_UNCOUNTED_FAILURE',
    CHG_EMPTY_LOCS_COUNTED_START : 'CHG_EMPTY_LOCS_COUNTED_START',
    CHG_EMPTY_LOCS_COUNTED_SUCCESS : 'CHG_EMPTY_LOCS_COUNTED_SUCCESS',
    CHG_EMPTY_LOCS_COUNTED_FAILURE : 'CHG_EMPTY_LOCS_COUNTED_FAILURE',
    CHG_EMPTY_LOCS_UNCOUNTED_START : 'CHG_EMPTY_LOCS_UNCOUNTED_START',
    CHG_EMPTY_LOCS_UNCOUNTED_SUCCESS : 'CHG_EMPTY_LOCS_UNCOUNTED_SUCCESS',
    CHG_EMPTY_LOCS_UNCOUNTED_FAILURE : 'CHG_EMPTY_LOCS_UNCOUNTED_FAILURE',

    // Count quantity overview action types
    CHG_EXPECTED_QTY_START: 'CHG_EXPECTED_QTY_START',
    CHG_EXPECTED_QTY_SUCCESS: 'CHG_EXPECTED_QTY_SUCCESS',
    CHG_EXPECTED_QTY_FAILURE: 'CHG_EXPECTED_QTY_FAILURE',
    CHG_VARIANCE_QTY_START: 'CHG_VARIANCE_QTY_START',
    CHG_VARIANCE_QTY_SUCCESS: 'CHG_VARIANCE_QTY_SUCCESS',
    CHG_VARIANCE_QTY_FAILURE: 'CHG_VARIANCE_QTY_FAILURE',

};

export default ProgressPageActionTypes;