const ProgressPageActionTypes = {
    // Active Locations Breakdown action types
    CHG_OCCUPIED_LOCS_COUNTED_START:'CHG_OCCUPIED_LOCS_COUNTED_START',
    CHG_OCCUPIED_LOCS_COUNTED_SUCCESS:'CHG_OCCUPIED_LOCS_COUNTED_SUCCESS',
    CHG_OCCUPIED_LOCS_COUNTED_FAILURE:'CHG_OCCUPIED_LOCS_COUNTED_FAILURE',
    CHG_OCCUPIED_LOCS_UNCOUNTED_START:'CHG_OCCUPIED_LOCS_UNCOUNTED_START',
    CHG_OCCUPIED_LOCS_UNCOUNTED_SUCCESS:'CHG_OCCUPIED_LOCS_UNCOUNTED_SUCCESS',
    CHG_OCCUPIED_LOCS_UNCOUNTED_FAILURE:'CHG_OCCUPIED_LOCS_UNCOUNTED_FAILURE',
    CHG_EMPTY_LOCS_COUNTED_START:'CHG_EMPTY_LOCS_COUNTED_START',
    CHG_EMPTY_LOCS_COUNTED_SUCCESS:'CHG_EMPTY_LOCS_COUNTED_SUCCESS',
    CHG_EMPTY_LOCS_COUNTED_FAILURE:'CHG_EMPTY_LOCS_COUNTED_FAILURE',
    CHG_EMPTY_LOCS_UNCOUNTED_START:'CHG_EMPTY_LOCS_UNCOUNTED_START',
    CHG_EMPTY_LOCS_UNCOUNTED_SUCCESS:'CHG_EMPTY_LOCS_UNCOUNTED_SUCCESS',
    CHG_EMPTY_LOCS_UNCOUNTED_FAILURE:'CHG_EMPTY_LOCS_UNCOUNTED_FAILURE',

    // Count quantity overview action types
    CHG_EXPECTED_QTY_START:'CHG_EXPECTED_QTY_START',
    CHG_EXPECTED_QTY_SUCCESS:'CHG_EXPECTED_QTY_SUCCESS',
    CHG_EXPECTED_QTY_FAILURE:'CHG_EXPECTED_QTY_FAILURE',
    CHG_VARIANCE_QTY_START:'CHG_VARIANCE_QTY_START',
    CHG_VARIANCE_QTY_SUCCESS:'CHG_VARIANCE_QTY_SUCCESS',
    CHG_VARIANCE_QTY_FAILURE:'CHG_VARIANCE_QTY_FAILURE',

    //Count Variance overview action types 
    CHG_UNIQUE_LOCS_COUNTED_START:'CHG_UNIQUE_LOCS_COUNTED_START',
    CHG_UNIQUE_LOCS_COUNTED_SUCCESS:'CHG_UNIQUE_LOCS_COUNTED_SUCCESS',
    CHG_UNIQUE_LOCS_COUNTED_FAILURE:'CHG_UNIQUE_LOCS_COUNTED_FAILURE',
    CHG_TOTAL_COUNTS_WITH_VARIANCE_START:'CHG_TOTAL_COUNTS_WITH_VARIANCE_START',
    CHG_TOTAL_COUNTS_WITH_VARIANCE_SUCCESS:'CHG_TOTAL_COUNTS_WITH_VARIANCE_SUCCESS',
    CHG_TOTAL_COUNTS_WITH_VARIANCE_FAILURE:'CHG_TOTAL_COUNTS_WITH_VARIANCE_FAILURE',

    //Problem Resolve Overview
    CHG_PR_START:"CHG_PR_START",
    CHG_PR_SUCCESS:"CHG_PR_SUCCESS",
    CHG_PR_FAILURE:"CHG_PR_FAILURE",

    //Damages overview 
    CHG_DMG_START : 'CHG_DMG_START',
    CHG_DMG_SUCCESS :'CHG_DMG_SUCCESS',
    CHG_DMG_FAILURE: 'CHG_DMG_FAILURE',
};

export default ProgressPageActionTypes;