const ProgressPageActionTypes = {
    // Active Locations Breakdown action types
    CHG_OCCUPIED_LOCS_COUNTED_START:'CHG_OCCUPIED_LOCS_COUNTED_START',
    CHG_OCCUPIED_LOCS_COUNTED_SUCCESS:'CHG_OCCUPIED_LOCS_COUNTED_SUCCESS',
    CHG_OCCUPIED_LOCS_COUNTED_FAILURE:'CHG_OCCUPIED_LOCS_COUNTED_FAILURE',
    CHG_OCCUPIED_LOCS_UNCOUNTED_START:'CHG_OCCUPIED_LOCS_UNCOUNTED_START',
    CHG_OCCUPIED_LOCS_UNCOUNTED_SUCCESS:'CHG_OCCUPIED_LOCS_UNCOUNTED_SUCCESS',
    CHG_OCCUPIED_LOCS_UNCOUNTED_FAILURE:'CHG_OCCUPIED_LOCS_UNCOUNTED_FAILURE',
    CHG_EMPTY_LOCS_COUNTED_START:'CHG_EMPTY_LOCS_COUNTED_START',
    CHG_EMPTY_LOCS_COUNTED_SUCCESS:'CHG_EMPTY_LOCS_COUNTED_SUCCESS',
    CHG_EMPTY_LOCS_COUNTED_FAILURE:'CHG_EMPTY_LOCS_COUNTED_FAILURE',
    CHG_EMPTY_LOCS_UNCOUNTED_START:'CHG_EMPTY_LOCS_UNCOUNTED_START',
    CHG_EMPTY_LOCS_UNCOUNTED_SUCCESS:'CHG_EMPTY_LOCS_UNCOUNTED_SUCCESS',
    CHG_EMPTY_LOCS_UNCOUNTED_FAILURE:'CHG_EMPTY_LOCS_UNCOUNTED_FAILURE',

    // Count quantity overview action types
    CHG_EXPECTED_QTY_START:'CHG_EXPECTED_QTY_START',
    CHG_EXPECTED_QTY_SUCCESS:'CHG_EXPECTED_QTY_SUCCESS',
    CHG_EXPECTED_QTY_FAILURE:'CHG_EXPECTED_QTY_FAILURE',
    CHG_VARIANCE_QTY_START:'CHG_VARIANCE_QTY_START',
    CHG_VARIANCE_QTY_SUCCESS:'CHG_VARIANCE_QTY_SUCCESS',
    CHG_VARIANCE_QTY_FAILURE:'CHG_VARIANCE_QTY_FAILURE',

    //Count Variance overview action types 
    CHG_UNIQUE_LOCS_COUNTED_START:'CHG_UNIQUE_LOCS_COUNTED_START',
    CHG_UNIQUE_LOCS_COUNTED_SUCCESS:'CHG_UNIQUE_LOCS_COUNTED_SUCCESS',
    CHG_UNIQUE_LOCS_COUNTED_FAILURE:'CHG_UNIQUE_LOCS_COUNTED_FAILURE',
    CHG_TOTAL_COUNTS_WITH_VARIANCE_START:'CHG_TOTAL_COUNTS_WITH_VARIANCE_START',
    CHG_TOTAL_COUNTS_WITH_VARIANCE_SUCCESS:'CHG_TOTAL_COUNTS_WITH_VARIANCE_SUCCESS',
    CHG_TOTAL_COUNTS_WITH_VARIANCE_FAILURE:'CHG_TOTAL_COUNTS_WITH_VARIANCE_FAILURE',

    //Problem Resolve Overview
    CHG_PR_START:"CHG_PR_START",
    CHG_PR_SUCCESS:"CHG_PR_SUCCESS",
    CHG_PR_FAILURE:"CHG_PR_FAILURE",

    //Damages overview 
    CHG_DMG_START : 'CHG_DMG_START',
    CHG_DMG_SUCCESS :'CHG_DMG_SUCCESS',
    CHG_DMG_FAILURE: 'CHG_DMG_FAILURE',

    //Not Putaway Overview
    CHG_NOT_PUTAWAY_0_START : 'CHG_NOT_PUTAWAY_0_START',
    CHG_NOT_PUTAWAY_0_SUCCESS :'CHG_NOT_PUTAWAY_0_SUCCESS',
    CHG_NOT_PUTAWAY_0_FAILURE: 'CHG_NOT_PUTAWAY_0_FAILURE',

    CHG_NOT_PUTAWAY_1_START : 'CHG_NOT_PUTAWAY_1_START',
    CHG_NOT_PUTAWAY_1_SUCCESS :'CHG_NOT_PUTAWAY_1_SUCCESS',
    CHG_NOT_PUTAWAY_1_FAILURE: 'CHG_NOT_PUTAWAY_1_FAILURE',

    CHG_NOT_PUTAWAY_2_START : 'CHG_NOT_PUTAWAY_2_START',
    CHG_NOT_PUTAWAY_2_SUCCESS :'CHG_NOT_PUTAWAY_2_SUCCESS',
    CHG_NOT_PUTAWAY_2_FAILURE: 'CHG_NOT_PUTAWAY_2_FAILURE',

    CHG_NOT_PUTAWAY_3_START : 'CHG_NOT_PUTAWAY_3_START',
    CHG_NOT_PUTAWAY_3_SUCCESS :'CHG_NOT_PUTAWAY_3_SUCCESS',
    CHG_NOT_PUTAWAY_3_FAILURE: 'CHG_NOT_PUTAWAY_3_FAILURE',

    CHG_NOT_PUTAWAY_4_START : 'CHG_NOT_PUTAWAY_4_START',
    CHG_NOT_PUTAWAY_4_SUCCESS :'CHG_NOT_PUTAWAY_4_SUCCESS',
    CHG_NOT_PUTAWAY_4_FAILURE: 'CHG_NOT_PUTAWAY_4_FAILURE',

    CHG_NOT_PUTAWAY_5_START : 'CHG_NOT_PUTAWAY_5_START',
    CHG_NOT_PUTAWAY_5_SUCCESS :'CHG_NOT_PUTAWAY_5_SUCCESS',
    CHG_NOT_PUTAWAY_5_FAILURE: 'CHG_NOT_PUTAWAY_5_FAILURE',

    CHG_NOT_PUTAWAY_6_START : 'CHG_NOT_PUTAWAY_6_START',
    CHG_NOT_PUTAWAY_6_SUCCESS :'CHG_NOT_PUTAWAY_6_SUCCESS',
    CHG_NOT_PUTAWAY_6_FAILURE: 'CHG_NOT_PUTAWAY_6_FAILURE',

    CHG_NOT_PUTAWAY_7_START : 'CHG_NOT_PUTAWAY_7_START',
    CHG_NOT_PUTAWAY_7_SUCCESS :'CHG_NOT_PUTAWAY_7_SUCCESS',
    CHG_NOT_PUTAWAY_7_FAILURE: 'CHG_NOT_PUTAWAY_7_FAILURE',

    CHG_NOT_PUTAWAY_OVER_7_START : 'CHG_NOT_PUTAWAY_OVER_7_START',
    CHG_NOT_PUTAWAY_OVER_7_SUCCESS :'CHG_NOT_PUTAWAY_OVER_7_SUCCESS',
    CHG_NOT_PUTAWAY_OVER_7_FAILURE: 'CHG_NOT_PUTAWAY_OVER_7_FAILURE',

    //Transitional Overview 
    CHG_TRANSITIONAL_0_START : 'CHG_TRANSITIONAL_0_START',
    CHG_TRANSITIONAL_0_SUCCESS :'CHG_TRANSITIONAL_0_SUCCESS',
    CHG_TRANSITIONAL_0_FAILURE: 'CHG_TRANSITIONAL_0_FAILURE',

    CHG_TRANSITIONAL_1_START : 'CHG_TRANSITIONAL_1_START',
    CHG_TRANSITIONAL_1_SUCCESS :'CHG_TRANSITIONAL_1_SUCCESS',
    CHG_TRANSITIONAL_1_FAILURE: 'CHG_TRANSITIONAL_1_FAILURE',

    CHG_TRANSITIONAL_2_START : 'CHG_TRANSITIONAL_2_START',
    CHG_TRANSITIONAL_2_SUCCESS :'CHG_TRANSITIONAL_2_SUCCESS',
    CHG_TRANSITIONAL_2_FAILURE: 'CHG_TRANSITIONAL_2_FAILURE',

    CHG_TRANSITIONAL_3_START : 'CHG_TRANSITIONAL_3_START',
    CHG_TRANSITIONAL_3_SUCCESS :'CHG_TRANSITIONAL_3_SUCCESS',
    CHG_TRANSITIONAL_3_FAILURE: 'CHG_TRANSITIONAL_3_FAILURE',

    CHG_TRANSITIONAL_4_START : 'CHG_TRANSITIONAL_4_START',
    CHG_TRANSITIONAL_4_SUCCESS :'CHG_TRANSITIONAL_4_SUCCESS',
    CHG_TRANSITIONAL_4_FAILURE: 'CHG_TRANSITIONAL_4_FAILURE',

    CHG_TRANSITIONAL_5_START : 'CHG_TRANSITIONAL_5_START',
    CHG_TRANSITIONAL_5_SUCCESS :'CHG_TRANSITIONAL_5_SUCCESS',
    CHG_TRANSITIONAL_5_FAILURE: 'CHG_TRANSITIONAL_5_FAILURE',

    CHG_TRANSITIONAL_6_START : 'CHG_TRANSITIONAL_6_START',
    CHG_TRANSITIONAL_6_SUCCESS :'CHG_TRANSITIONAL_6_SUCCESS',
    CHG_TRANSITIONAL_6_FAILURE: 'CHG_TRANSITIONAL_6_FAILURE',

    CHG_TRANSITIONAL_7_START : 'CHG_TRANSITIONAL_7_START',
    CHG_TRANSITIONAL_7_SUCCESS :'CHG_TRANSITIONAL_7_SUCCESS',
    CHG_TRANSITIONAL_7_FAILURE: 'CHG_TRANSITIONAL_7_FAILURE',

    CHG_TRANSITIONAL_OVER_7_START : 'CHG_TRANSITIONAL_OVER_7_START',
    CHG_TRANSITIONAL_OVER_7_SUCCESS :'CHG_TRANSITIONAL_OVER_7_SUCCESS',
    CHG_TRANSITIONAL_OVER_7_FAILURE: 'CHG_TRANSITIONAL_OVER_7_FAILURE',

};

export default ProgressPageActionTypes;