const FileUploadActionTypes = {
    FILE_UPLOAD_START:'FILE_UPLOAD_START',
    FILE_UPLOAD_SUCCESS:'FILE_UPLOAD_SUCCESS',
    FILE_UPLOAD_FAILURE:'FILE_UPLOAD_FAILURE',
};

export default FileUploadActionTypes;