const FileUploadActionTypes = {
    CHG_FILE_UPLOAD_START:'CHG_FILE_UPLOAD_START',
    CHG_FILE_UPLOAD_SUCCESS:'CHG_FILE_UPLOAD_SUCCESS',
    CHG_FILE_UPLOAD_FAILURE:'CHG_FILE_UPLOAD_FAILURE',

    FSC_FILE_UPLOAD_START:'FILE_UPLOAD_START',
    FSC_FILE_UPLOAD_SUCCESS:'FILE_UPLOAD_SUCCESS',
    FSC_FILE_UPLOAD_FAILURE:'FILE_UPLOAD_FAILURE',
};

export default FileUploadActionTypes;