 
 export const ShrinkPageActionTypes = {
     
     CHG_DAILY_SHRINK_DATA_START:'CHG_DAILY_SHRINK_DATA_START',
     CHG_DAILY_SHRINK_DATA_SUCCESS:'CHG_DAILY_SHRINK_DATA_SUCCESS',
     CHG_DAILY_SHRINK_DATA_FAILURE:'CHG_DAILY_SHRINK_DATA_SUCCESS',
    
     CHG_WEEKLY_SHRINK_DATA_START:'CHG_WEEKLY_SHRINK_DATA_START',
     CHG_WEEKLY_SHRINK_DATA_SUCCESS:'CHG_WEEKLY_SHRINK_DATA_SUCCESS',
     CHG_WEEKLY_SHRINK_DATA_FAILURE:'CHG_WEEKLY_SHRINK_DATA_FAILURE',
    
     CHG_MONTHLY_SHRINK_DATA_START :'CHG_MONTHLY_SHRINK_DATA_START',
     CHG_MONTHLY_SHRINK_DATA_SUCCESS :'CHG_MONTHLY_SHRINK_DATA_SUCCESS',
     CHG_MONTHLY_SHRINK_DATA_FAILURE:'CHG_MONTHLY_SHRINK_DATA_FAILURE',
    
     CHG_YEARLY_SHRINK_DATA_START:'CHG_YEARLY_SHRINK_DATA_START',
     CHG_YEARLY_SHRINK_DATA_SUCCESS:'CHG_YEARLY_SHRINK_DATA_SUCCESS',
     CHG_YEARLY_SHRINK_DATA_FAILURE:'CHG_YEARLY_SHRINK_DATA_FAILURE',
    
     FSC_DAILY_SHRINK_DATA_START:'FSC_DAILY_SHRINK_DATA_START',
     FSC_DAILY_SHRINK_DATA_SUCCESS:'FSC_DAILY_SHRINK_DATA_SUCCESS',
     FSC_DAILY_SHRINK_DATA_FAILURE:'FSC_DAILY_SHRINK_DATA_SUCCESS',
     
     FSC_WEEKLY_SHRINK_DATA_START:'FSC_WEEKLY_SHRINK_DATA_START',
     FSC_WEEKLY_SHRINK_DATA_SUCCESS:'FSC_WEEKLY_SHRINK_DATA_SUCCESS',
     FSC_WEEKLY_SHRINK_DATA_FAILURE:'FSC_WEEKLY_SHRINK_DATA_FAILURE',
     
     FSC_MONTHLY_SHRINK_DATA_START :'FSC_MONTHLY_SHRINK_DATA_START',
     FSC_MONTHLY_SHRINK_DATA_SUCCESS :'FSC_MONTHLY_SHRINK_DATA_SUCCESS',
     FSC_MONTHLY_SHRINK_DATA_FAILURE:'FSC_MONTHLY_SHRINK_DATA_FAILURE',
     
     FSC_YEARLY_SHRINK_DATA_START:'FSC_YEARLY_SHRINK_DATA_START',
     FSC_YEARLY_SHRINK_DATA_SUCCESS:'FSC_YEARLY_SHRINK_DATA_SUCCESS',
     FSC_YEARLY_SHRINK_DATA_FAILURE:'FSC_YEARLY_SHRINK_DATA_FAILURE',
 };

 export default ShrinkPageActionTypes;